# cs/labs/bash/BUILD
package(default_visibility = ["//visibility:public"])

sh_test(
    name = "hello_world_test_gpt_sh",
    srcs = ["hello_world_test.gpt.sh"],
    data = [
        "BUILD",
        "acl.json",
        "hello_world.gpt.sh",
    ],
)
