# cs/apps/BUILD
load("@rules_cc//cc:defs.bzl", "cc_library")
load("@rules_python//python:defs.bzl", "py_binary")

package(default_visibility = ["//visibility:public"])

# cs/apps/BUILD
# Placeholder BUILD to mark Bazel package.

config_setting(
    name = "host_amd64",
    constraint_values = ["@platforms//cpu:x86_64"],
)

config_setting(
    name = "host_arm64",
    constraint_values = ["@platforms//cpu:arm64"],
)
