# cs/apps/trycopilot.ai/protos/BUILD
load("@rules_cc//cc:defs.bzl", "cc_library")
load("//cs/net/proto/codegen:proto_codegen.bzl", "proto_codegen_cc_library")

package(default_visibility = ["//visibility:public"])

proto_codegen_cc_library(
    name = "acl.proto",
    decl = "acl.proto.hh",
)

proto_codegen_cc_library(
    name = "overland.proto",
    decl = "overland.proto.hh",
)

proto_codegen_cc_library(
    name = "user.proto",
    decl = "user.proto.hh",
)

proto_codegen_cc_library(
    name = "auth.proto",
    decl = "auth.proto.hh",
)

proto_codegen_cc_library(
    name = "uuid.proto",
    decl = "uuid.proto.hh",
)

proto_codegen_cc_library(
    name = "web_app_meta.proto",
    decl = "web_app_meta.proto.hh",
)

proto_codegen_cc_library(
    name = "matrix.proto",
    decl = "matrix.proto.hh",
)

proto_codegen_cc_library(
    name = "log.proto",
    decl = "log.proto.hh",
)

proto_codegen_cc_library(
    name = "game.proto",
    decl = "game.proto.hh",
)

proto_codegen_cc_library(
    name = "prompt.proto",
    decl = "prompt.proto.hh",
)

proto_codegen_cc_library(
    name = "prompt_driver.proto",
    decl = "prompt_driver.proto.hh",
)

proto_codegen_cc_library(
    name = "ui.proto",
    decl = "ui.proto.hh",
)

proto_codegen_cc_library(
    name = "config.proto",
    decl = "config.proto.hh",
)
