# cs/labs/julia/BUILD
package(default_visibility = ["//visibility:public"])

py_test(
    name = "hello_world_test_gpt_py",
    srcs = ["hello_world_test.gpt.py"],
    data = [
        "hello_world.gpt.jl",
    ],
    main = "hello_world_test.gpt.py",
)
