# cs/apps/scribe-service/protos/BUILD
load("//cs/net/proto/codegen:proto_codegen.bzl", "proto_codegen_cc_library")

package(default_visibility = ["//visibility:public"])

proto_codegen_cc_library(
    name = "config.proto",
    decl = "config.proto.hh",
)

proto_codegen_cc_library(
    name = "job.proto",
    decl = "job.proto.hh",
)

proto_codegen_cc_library(
    name = "upload.proto",
    decl = "upload.proto.hh",
)
