package(default_visibility = ["//visibility:public"])

cc_library(
    name = "dom",
    hdrs = ["dom.hh"],
    deps = [
        "//cs:log",
        "//cs:result",
        "//cs/parsers",
    ],
)

cc_library(
    name = "minify",
    hdrs = ["minify.hh"],
    deps = [
        "//cs:log",
        "//cs:result",
        "//cs/parsers",
    ],
)
