# cs/apps/trycopilot.ai/emscripten/BUILD
package(default_visibility = ["//visibility:public"])

cc_library(
    name = "emscripten",
    srcs = ["emscripten.cc"],
    hdrs = ["emscripten.hh"],
    deps = [
        "//cs/net/http:request",
        "//cs/net/http:response",
        "//cs/net/json:object",
        "//cs/net/json:parsers",
    ],
)
