package(default_visibility = ["//visibility:public"])

cc_library(
    name = "parsers",
    srcs = ["parsers.cc"],
    hdrs = ["parsers.hh"],
    deps = [
        "//cs:log",
        "//cs:result",
        "//cs/util:fmt",
    ],
)
