# cs/apps/message-queue/protos/BUILD
load("//cs/net/proto/codegen:proto_codegen.bzl", "proto_codegen_cc_library")

package(default_visibility = ["//visibility:public"])

proto_codegen_cc_library(
    name = "config.proto",
    decl = "config.proto.hh",
)

proto_codegen_cc_library(
    name = "queue.proto",
    decl = "queue.proto.hh",
)
