# cs/apps/cite.pub/protos/BUILD
load("//cs/net/proto/codegen:proto_codegen.bzl", "proto_codegen_cc_library")

package(default_visibility = ["//visibility:public"])

proto_codegen_cc_library(
    name = "config.proto",
    decl = "config.proto.hh",
)

proto_codegen_cc_library(
    name = "save_resource_form.gpt.proto",
    decl = "save_resource_form.gpt.proto.hh",
)

proto_codegen_cc_library(
    name = "get_cached_page_request.gpt.proto",
    decl = "get_cached_page_request.gpt.proto.hh",
)

proto_codegen_cc_library(
    name = "lookup_mapping.proto",
    decl = "lookup_mapping.proto.hh",
)
