# cs/apps/trycopilot.ai/text/BUILD
package(default_visibility = ["//visibility:public"])

# Render text in a graphics GUI from scratch

cc_binary(
    name = "draw_to_console",
    srcs = ["draw_to_console.cc"],
    deps = ["//cs/apps/trycopilot.ai/text/fonts:mono"],
)
