# cs/apps/trycopilot.ai/net/BUILD
package(default_visibility = ["//visibility:public"])

cc_library(
    name = "ws",
    srcs = ["ws.cc"],
    hdrs = ["ws.hh"],
    deps = [
        "//cs:log",
        "//cs:result",
        "//cs/net/http:request",
        "//cs/net/http:response",
    ],
)
